const products=[
  { "id": 1, "category": "Laptop", "name": "Dell Inspiron 15", "brand": "Dell", "price": 65000, "specs": { "processor": "Intel i5", "ram": "8GB", "storage": "512GB SSD" } },
  { "id": 2, "category": "Laptop", "name": "HP Pavilion 14", "brand": "HP", "price": 72000, "specs": { "processor": "Intel i7", "ram": "16GB", "storage": "1TB SSD" } },
  { "id": 3, "category": "Laptop", "name": "MacBook Air M1", "brand": "Apple", "price": 98000, "specs": { "processor": "Apple M1", "ram": "16GB", "storage": "512GB" } },
  { "id": 4, "category": "Laptop", "name": "Lenovo IdeaPad Slim 5", "brand": "Lenovo", "price": 78000, "specs": { "processor": "AMD Ryzen 7", "ram": "16GB", "storage": "512GB" } },
  { "id": 5, "category": "Laptop", "name": "Asus VivoBook 16", "brand": "Asus", "price": 60000, "specs": { "processor": "Intel i5", "ram": "8GB", "storage": "512GB SSD" } },
  { "id": 6, "category": "Phone", "name": "iPhone 14", "brand": "Apple", "price": 70000, "specs": { "display": "6.1 inch", "storage": "128GB", "camera": "12MP" } },
  { "id": 7, "category": "Phone", "name": "Samsung Galaxy S23", "brand": "Samsung", "price": 68000, "specs": { "display": "6.2 inch", "storage": "256GB", "camera": "50MP" } },
  { "id": 8, "category": "Phone", "name": "OnePlus 11", "brand": "OnePlus", "price": 56000, "specs": { "display": "6.7 inch", "storage": "256GB", "camera": "50MP" } },
  { "id": 9, "category": "Phone", "name": "Redmi Note 13 Pro", "brand": "Xiaomi", "price": 28000, "specs": { "display": "6.67 inch", "storage": "128GB", "camera": "108MP" } },
  { "id": 10, "category": "Phone", "name": "Realme GT Neo", "brand": "Realme", "price": 25000, "specs": { "display": "6.43 inch", "storage": "128GB", "camera": "64MP" } },
  { "id": 11, "category": "Tablet", "name": "iPad 10th Gen", "brand": "Apple", "price": 42000, "specs": { "display": "10.9 inch", "ram": "8GB", "storage": "64GB" } },
  { "id": 12, "category": "Tablet", "name": "Samsung Galaxy Tab S8", "brand": "Samsung", "price": 62000, "specs": { "display": "11 inch", "ram": "16GB", "storage": "256GB" } },
  { "id": 13, "category": "Tablet", "name": "Lenovo Tab P11", "brand": "Lenovo", "price": 23000, "specs": { "display": "11 inch", "ram": "4GB", "storage": "64GB" } },
  { "id": 14, "category": "Tablet", "name": "Xiaomi+-- Pad 6", "brand": "Xiaomi", "price": 27000, "specs": { "display": "11 inch", "ram": "8GB", "storage": "128GB" } },
  { "id": 15, "category": "Tablet", "name": "Realme Pad X", "brand": "Realme", "price": 19000, "specs": { "display": "10.95 inch", "ram": "4GB", "storage": "64GB" } },
  { "id": 16, "category": "Charger", "name": "Apple 20W Adapter", "brand": "Apple", "price": 1900, "specs": { "power": "20W", "port": "USB-C" } },
  { "id": 17, "category": "Charger", "name": "Samsung 25W Fast Charger", "brand": "Samsung", "price": 1500, "specs": { "power": "25W", "port": "USB-C" } },
  { "id": 18, "category": "Charger", "name": "Anker 65W Charger", "brand": "Anker", "price": 3200, "specs": { "power": "65W", "port": "USB-C" } },
  { "id": 19, "category": "Charger", "name": "Mi 33W Charger", "brand": "Xiaomi", "price": 1200, "specs": { "power": "33W", "port": "USB-C" } },
  { "id": 20, "category": "Charger", "name": "Realme SuperDart", "brand": "Realme", "price": 1800, "specs": { "power": "50W", "port": "USB-C" } },
  { "id": 21, "category": "Headphones", "name": "Sony WH-1000XM5", "brand": "Sony", "price": 29000, "specs": { "type": "Over-ear", "noiseCancellation": true } },
  { "id": 22, "category": "Headphones", "name": "Boat Rockerz 450", "brand": "Boat", "price": 1500, "specs": { "type": "On-ear", "wireless": true } },
  { "id": 23, "category": "Headphones", "name": "JBL Tune 760NC", "brand": "JBL", "price": 8000, "specs": { "type": "Over-ear", "noiseCancellation": true } },
  { "id": 24, "category": "Headphones", "name": "Apple AirPods Pro", "brand": "Apple", "price": 25000, "specs": { "type": "In-ear", "noiseCancellation": true } },
  { "id": 25, "category": "Headphones", "name": "Nothing Ear (2)", "brand": "Nothing", "price": 10000, "specs": { "type": "In-ear", "wireless": true } },
  { "id": 26, "category": "Smartwatch", "name": "Apple Watch SE", "brand": "Apple", "price": 30000, "specs": { "display": "1.78 inch", "battery": "18 hrs" } },
  { "id": 27, "category": "Smartwatch", "name": "Samsung Galaxy Watch 6", "brand": "Samsung", "price": 29000, "specs": { "display": "1.4 inch", "battery": "40 hrs" } },
  { "id": 28, "category": "Smartwatch", "name": "Boat Wave Pro", "brand": "Boat", "price": 3000, "specs": { "display": "1.75 inch", "battery": "7 days" } },
  { "id": 29, "category": "Smartwatch", "name": "Noise ColorFit Ultra", "brand": "Noise", "price": 4500, "specs": { "display": "1.9 inch", "battery": "10 days" } },
  { "id": 30, "category": "Smartwatch", "name": "Fire-Boltt Phoenix", "brand": "Fire-Boltt", "price": 3500, "specs": { "display": "1.8 inch", "battery": "8 days" } },
  { "id": 31, "category": "Monitor", "name": "LG 27 inch IPS", "brand": "LG", "price": 22000, "specs": { "size": "27 inch", "resolution": "1080p" } },
  { "id": 32, "category": "Monitor", "name": "Samsung Curved Monitor", "brand": "Samsung", "price": 18000, "specs": { "size": "24 inch", "curved": true } },
  { "id": 33, "category": "Monitor", "name": "Dell UltraSharp", "brand": "Dell", "price": 35000, "specs": { "size": "27 inch", "resolution": "1440p" } },
  { "id": 34, "category": "Monitor", "name": "Acer Nitro Gaming", "brand": "Acer", "price": 20000, "specs": { "size": "24 inch", "refreshRate": "144Hz" } },
  { "id": 35, "category": "Monitor", "name": "BenQ Eye Care", "brand": "BenQ", "price": 17000, "specs": { "size": "27 inch", "eyeCare": true } },
  { "id": 36, "category": "Keyboard", "name": "Logitech MX Keys", "brand": "Logitech", "price": 9000, "specs": { "type": "Wireless", "layout": "Full" } },
  { "id": 37, "category": "Keyboard", "name": "Redragon Mechanical", "brand": "Redragon", "price": 4000, "specs": { "type": "Mechanical", "backlight": true } },
  { "id": 38, "category": "Mouse", "name": "Logitech MX Master 3", "brand": "Logitech", "price": 8500, "specs": { "type": "Wireless", "dpi": "4000" } },
  { "id": 39, "category": "Mouse", "name": "HP Wireless Mouse", "brand": "HP", "price": 1200, "specs": { "type": "Wireless", "dpi": "1600" } },
  { "id": 40, "category": "Mouse", "name": "Razer DeathAdder", "brand": "Razer", "price": 4500, "specs": { "type": "Wired", "dpi": "16000" } },
  { "id": 41, "category": "Power Bank", "name": "Mi Power Bank 20000mAh", "brand": "Xiaomi", "price": 2200, "specs": { "capacity": "20000mAh", "ports": 2 } },
  { "id": 42, "category": "Power Bank", "name": "Anker PowerCore", "brand": "Anker", "price": 3500, "specs": { "capacity": "20000mAh", "ports": 3 } },
  { "id": 43, "category": "Power Bank", "name": "Realme Power Bank", "brand": "Realme", "price": 1800, "specs": { "capacity": "10000mAh", "ports": 2 } },
  { "id": 44, "category": "Power Bank", "name": "Samsung Power Bank", "brand": "Samsung", "price": 2500, "specs": { "capacity": "15000mAh", "ports": 2 } },
  { "id": 45, "category": "Power Bank", "name": "Ambrane 10000mAh", "brand": "Ambrane", "price": 1200, "specs": { "capacity": "10000mAh", "ports": 2 } },
  { "id": 46, "category": "Camera", "name": "Canon EOS 1500D", "brand": "Canon", "price": 38000, "specs": { "sensor": "24MP", "lens": "18-55mm" } },
  { "id": 47, "category": "Camera", "name": "Nikon D5600", "brand": "Nikon", "price": 52000, "specs": { "sensor": "24MP", "lens": "18-140mm" } },
  { "id": 48, "category": "Camera", "name": "Sony Alpha A6400", "brand": "Sony", "price": 72000, "specs": { "sensor": "24MP", "video": "4K" } },
  { "id": 49, "category": "Camera", "name": "GoPro Hero 11", "brand": "GoPro", "price": 45000, "specs": { "video": "5.3K", "waterproof": true } },
  { "id": 50, "category": "Camera", "name": "DJI Osmo Action", "brand": "DJI", "price": 38000, "specs": { "video": "4K", "waterproof": true } }
]
module.exports = products;
